### PR TITLE
2018-07-26.md / Jul 26 2018 IR IG meeting notes

### PR DESCRIPTION
**Pull request by DiegoPino**
Agenda/notes based on https://docs.google.com/document/d/1IpFSUFM8HfEaQIv008W6lxmCUwl_Xm-Wxs0V0fPWEZQ/edit#
Notes merged from mine own faulty note taking + Joanna's LASIR ones.

@bryjbrown let me know if something is missing

### CODE REVIEW

**Comment by DiegoPino** [comment]
@bryjbrown @DonRichards ping what happened with this one? I opened this pull 2 weeks ago =(

**Comment by DiegoPino** [comment]
@manez hey, could you verify for me that IG are using github at all? Kinda confused about the contributing procedure here *and also about note taking* 😬  if pulls are not being seeing/merged and direct references to members neither, Thanks!

**Comment by manez** [comment]
@DiegoPino each IG repo is used however each IG sees fit, as decided by the convenors - but I'll double check with an outside-of-github email to make sure that @bryjbrown and @DonRichards  are receiving their notifications from this one.

**Comment by DiegoPino** [comment]
Muchas gracias @manez, really appreciate it.

**Comment by DonRichards** [comment]
Sorry but I don't have write access to this repo so I can't merge.

**Comment by manez** [comment]
Well! *that* I can fix...

**Comment by bryjbrown** [comment]
@DiegoPino Whoops! I never got any GitHub notifications about this, and I don't typically watch this repo very frequently. Apologies, I'll straighten this out.

**Pull request merged**
